# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and coverage reports
      run: |
        pytest --cov tests --cov scoretracker --cov-report=
        # tests should have 100% coverage
        coverage report --omit "scoretracker/*" --fail-under=100
        # app code can have less coverage
        coverage report --omit "tests/*" --fail-under=75
